<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" name="Test1(failed)">
    <classes>
      <class name="api.ChainingEndToEnd.CreatUser">
        <methods>
          <include name="test_createUser" invocation-numbers="0"/>
        </methods>
      </class> <!-- api.ChainingEndToEnd.CreatUser -->
    </classes>
  </test> <!-- Test1(failed) -->
  <test thread-count="5" name="Test2(failed)">
    <classes>
      <class name="api.ChainingEndToEnd.GetUser">
        <methods>
          <include name="test_getUser" invocation-numbers="0"/>
        </methods>
      </class> <!-- api.ChainingEndToEnd.GetUser -->
    </classes>
  </test> <!-- Test2(failed) -->
  <test thread-count="5" name="Test3(failed)">
    <classes>
      <class name="api.ChainingEndToEnd.UpdateUser">
        <methods>
          <include name="test_updateUser" invocation-numbers="0"/>
        </methods>
      </class> <!-- api.ChainingEndToEnd.UpdateUser -->
    </classes>
  </test> <!-- Test3(failed) -->
  <test thread-count="5" name="Test4(failed)">
    <classes>
      <class name="api.ChainingEndToEnd.DeleteUser">
        <methods>
          <include name="test_deleteUser" invocation-numbers="0"/>
        </methods>
      </class> <!-- api.ChainingEndToEnd.DeleteUser -->
    </classes>
  </test> <!-- Test4(failed) -->
</suite> <!-- Failed suite [Suite] -->
